package com.huahua.mapper.system;

import com.huahua.domain.system.SmRoleMenu;
import java.util.List;

public interface SmRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_menu
     *
     * @mbggenerated
     */
    int insert(SmRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_menu
     *
     * @mbggenerated
     */
    SmRoleMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_menu
     *
     * @mbggenerated
     */
    List<SmRoleMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmRoleMenu record);
}