package com.huahua.mapper.system;


import com.huahua.domain.system.SmRole;

import java.util.List;

public interface SmRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role
     *
     * @mbggenerated
     */
    int insert(SmRole record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role
     *
     * @mbggenerated
     */
    SmRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role
     *
     * @mbggenerated
     */
    List<SmRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmRole record);
}