package com.huahua.mapper.system;

import com.huahua.domain.system.SmSite;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SmSiteMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sm_site
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sm_site
	 *
	 * @mbggenerated
	 */
	int insert(SmSite record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sm_site
	 *
	 * @mbggenerated
	 */
	SmSite selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sm_site
	 *
	 * @mbggenerated
	 */
	List<SmSite> selectAll();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sm_site
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SmSite record);
}