package com.huahua.mapper.system;

import com.huahua.domain.system.SmUserRole;
import java.util.List;

public interface SmUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_role
     *
     * @mbggenerated
     */
    int insert(SmUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_role
     *
     * @mbggenerated
     */
    SmUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_role
     *
     * @mbggenerated
     */
    List<SmUserRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmUserRole record);

    /**
     * @Description: 根据用户id查需用户角色
     * @Param: 
     * @return: 
     */
    SmUserRole selectByUserId(Integer id);
}